### ISSUE TITLE
Include and exclude tables in the analyze command

### ISSUE THREAD

**Issue by dirkgroenen** [sodadata/soda-core#1091]
_Originally posted by @mmigdiso, but accidentally transferred._

By default, soda fetches all of the tables and starts analyzing them. This is not always a wanted scenario. Specially if the schema has hundreds of tables some of which may not need to be covered by DQ. 

I propose having an include_tables/exclude_tables property in the warehouse.yml file. 
ex: 
```
name: redshift
connection:
  type: redshift
  host: testtest
  username: env_var(REDSHIFT_USERNAME)
  password: env_var(REDSHIFT_PASSWORD)
  region:  XXXX
  database: DB
  schema: test_schema
  tables_included:
    - table_to_be_included
```

_Comment from tombaeyens_

> It's better to do it as options on the analyze command. They should also support wildcards like PRD_*
