### ISSUE TITLE
Change over time checks fail with `AttributeError: 'NoneType' object has no attribute 'get'`

### ISSUE THREAD

**Issue by dirkgroenen** [sodadata/soda-core#1150]
When running the following checks with a valid Soda Cloud connection I get an error:

```yaml
checks for CUSTOMERS:

  # Detailed schema expectations control
  - schema:
      fail:
        when required column missing: ['id', 'size', 'distance']
        when forbidden column present: ['email_address', 'pii_%']
        when wrong column type:
          id: varchar
          distance: integer
        when wrong column index:
          id: 0

      # And/or simple notifications on any schema change:
      warn:
        when schema changes: any
```

The error returned is: 
```
Unknown error while executing scan.
  | 'NoneType' object has no attribute 'get'
  | Stacktrace:
  | Traceback (most recent call last):
  |   File "/home/dirk/work/soda/code/meuk/data-council-workshop/.venv/lib/python3.8/site-packages/soda/scan.py", line 339, in execute
  |     historic_value = historic_data.get(historic_descriptor)
  | AttributeError: 'NoneType' object has no attribute 'get'
```
