### ISSUE TITLE
Check `for each` doesn't support `schema.table_name`

### ISSUE THREAD

**Issue by jasonicarter** [sodadata/soda-core#1162]
The `for each table T:` check works for `<table_name>` but not `<schema.table_name>` unlike, and as expected, the `checks for` check which supports `<schema.table_name>` 

**Example Checks.yml**
```yaml
# Not working...
for each table T:
  tables:
    - android.application_installed
  checks:
    - row_count > 0

# Working...
checks for android.application_installed:
  - row_count > 0
```

**Result - for each table T:**
```shell
$ soda scan -d raw -c configuration.yml -V checks/checks.yml
Soda Core 3.0.0b4
Reading configuration file "configuration.yml"
Reading SodaCL file "checks/checks.yml"
Cross data source table sets not yet supported. android.application_installed refers to non default data source  android. Default data source is raw
Scan execution starts
Query raw.for_each_table_T[0]:
SELECT table_name 
FROM information_schema.tables
Query raw.APPLICATION_INSTALLED.aggregation[0]:
```

**Result - checks for:**
```shell
$ soda scan -d raw -c configuration.yml -V checks/checks.yml
Soda Core 3.0.0b4
Reading configuration file "configuration.yml"
Reading SodaCL file "checks/checks.yml"
Scan execution starts
Query raw.android.application_installed.aggregation[0]:
SELECT 
  COUNT(*) 
FROM android.application_installed
```
