### ISSUE TITLE
For each must filter on schema

### ISSUE THREAD

**Issue by jasonicarter** [sodadata/soda-core#1167]
Using the **only** wildcard, `%`, with the `for each` check does not include the datasource schema resulting in a query which scans all tables within the `information_schema.tables` table.

QUERY PRODUCE...
```SQL
SELECT table_name
FROM information_schema.tables
WHERE (lower(table_name) like '%');
```

SHOULD BE...
```SQL
SELECT table_name
FROM information_schema.tables
WHERE (lower(table_name) like '%')
AND lower(table_schema) = '[SCHEMA_NAME]';
```
---
**Soda Scan**
```shell
soda scan -d raw_stripe stitch_stripe.yml
```
**Configuration**
```yaml
data_source raw_stripe:
  type: snowflake
  connection:
    username: ${SNOWFLAKE_USER}
    password: ${SNOWFLAKE_PASSWORD}
    account: ${SNOWFLAKE_ACCOUNT}
    database: RAW
    schema: STRIPE
    warehouse: my_warehouse
    role: my_role
```
**Check**
```yaml
for each table T:
  tables:
    - raw_stripe.charges # works
    - raw_stripe.% # works but queries all tables
    - '%' # works but queries all tables 
  checks:
    - row_count > 0
```
**Result**
Queries `[RANDOM]` tables not in the schema which results in execution errors
```shell
Soda Core 3.0.0b4
Reading configuration file "configuration.yml"
Adding SodaCL dir checks/raw/
Reading SodaCL file "checks/raw/stitch_stripe.yml"
Scan execution starts
Query raw_stripe.for_each_table_T[0]:
SELECT table_name 
FROM information_schema.tables
WHERE (lower(table_name) like '%')

Query raw_stripe.[RANDOM_TABLE].aggregation[0]:
SELECT 
  COUNT(*) 
FROM [RANDOM_TABLE].
Query execution error in raw_stripe.[RANDOM_TABLE]..aggregation[0]: 002003 (42S02): SQL compilation error:
Object '[RANDOM_TABLE].' does not exist or not authorized.

[...] -- ALL other tables in `information_schema.tables`
```
