### ISSUE TITLE
For each with table filters.

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-core#1173]
e.g.

```
filter EVENT_TABLE_% [hourly]:
  where: TIMESTAMP '${ts_start}' <= event_time AND event_time > dateadd(hour, -1, created_at)

for each table T:
  tables:
    - EVENT_TABLE_% [hourly]
  checks:
    - row_count > 0

    -

``` 

via https://soda-community.slack.com/archives/C038FFU79J5/p1648393195437059

**Comment by tombaeyens** [comment]
I think this feature request would make sense even without variable mapping.  But it would be great to get confirmation for this.

@jasonicarter For your use case, do you need to map variables or would the filter variables be the same for all the tables referenced in the for-each?

**Comment by jasonicarter** [comment]
@tombaeyens for my specific use case I would use the same filter for all tables referenced in the `for each` check. And for other table filters I would just separate that out into a different check within the same iml file.
```yaml
# Hourly checks
for each table T1:
  tables:
    - EVENT_TABLE_% [hourly]
  checks:
    - row_count > 0

# Daily checks
 for each table T2:
  tables:
    - EVENT_TABLE_% [daily]
  checks:
    - missing_percentage(user_id) > 1%
```
