### ISSUE TITLE
For each improve logging

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-core#1187]
For each, when used as designed, works perfectly:
```yaml
for each table T:
 tables:
  - sodatest_customers_b7580920
  - sodatest_orders_f7532be6
 checks:
  - count > 0
```
```
soda scan -d local_postgres_sodasql -c ~/.soda/configuration.yaml -ch checks.yaml
Soda Core 0.0.1
Scan summary:
2/2 checks PASSED: 
  sodatest_customers_b7580920 in local_postgres_sodasql
   count > 0 [PASSED]
  sodatest_orders_f7532be6 in local_postgres_sodasql
   count > 0 [PASSED]
All is good. No failures. No warnings. No errors.
```

But, because I’m a dummy, I was initially using the For Each check to check columns in a single table instead of tables/dataset in data source. Even though it CLEARLY says tables in the checks file. Duh. But the CLI output showed me all tests passed everything was fine, even though there was no way it could’ve found non-existent table names like `id` and `size`.  Could we add something so that for each errors out if the input are non-table names? For me and the other stoopids of the world?
```yaml
for each table T:
 tables:
  - id
  - size
 checks:
  - count > 0
```
```
scan -d local_postgres_sodasql -c ~/.soda/configuration.yaml -ch checks.yaml
Soda Core 0.0.1
Scan summary:
All is good. No failures. No warnings. No errors.
```
