### ISSUE TITLE
Improved CLI output - Invalid & missing

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-core#1190]
A couple of unexpected things with this check. I copy+pasted this out of the docs, changing only the column name and adding the extra check for `count > 0`.
```yaml
checks for sodatest_customers_b7580920:
 - count > 0
 - invalid_percent(country) < 1%:
   missing values: [N/A, No value, null]
```

And the output confused me.

- First, because it advised that `Only strings or only numbers allowed in missing values: [‘N/A’, ‘No value’, None]`
- and secondly, because it executed the check anyway and found that it passed! 

Of course, it has no correct missing values to check against, but I would expect that if the missing values errors out, the check that uses the missing values would also error out, or at least not pass.

```
soda scan -d local_postgres_sodasql -c ~/.soda/configuration.yaml -ch checks.yaml
Soda Core 0.0.1
Only strings or only numbers allowed in missing values: ['N/A', 'No value', None]
 +-> line=4,col=7 in checks.yaml
Counting invalid without valid specification does not make sense
Scan summary:
2/2 checks PASSED: 
  sodatest_customers_b7580920 in local_postgres_sodasql
   count > 0 [PASSED]
   invalid_percent(country) < 1% [PASSED]
1 errors.
Oops! 1 error. 0 failures. 0 warnings. 2 pass.
ERRORS:
Only strings or only numbers allowed in missing values: ['N/A', 'No value', None]
 +-> line=4,col=7 in checks.yaml
```

This one worked, though, without the square brackets. Though now it occurs to me that the square brackets are perhaps not needed in the check, but were in the docs to communicate "these are your options for the value to put here".
```yaml
checks for sodatest_customers_b7580920:
 - count > 0
 - invalid_percent(country) < 1%:
   missing values: N/A
```
```
soda scan -d local_postgres_sodasql -c ~/.soda/configuration.yaml -ch checks.yaml
Soda Core 0.0.1
Counting invalid without valid specification does not make sense
Scan summary:
2/2 checks PASSED: 
  sodatest_customers_b7580920 in local_postgres_sodasql
   count > 0 [PASSED]
   invalid_percent(country) < 1% [PASSED]
All is good. No failures. No warnings. No errors.
```

And this did not work as expected. Though I was hoping the error message might tell me what I think I have already deduced, that you can only use a string for missing values, not a list.
```yaml
checks for sodatest_customers_b7580920:
 - count > 0
 - invalid_percent(country) < 1%:
   missing values: N/A, None
```
```
soda scan -d local_postgres_sodasql -c ~/.soda/configuration.yaml -ch checks.yaml
Soda Core 0.0.1
Counting invalid without valid specification does not make sense
Scan summary:
2/2 checks PASSED: 
  sodatest_customers_b7580920 in local_postgres_sodasql
   count > 0 [PASSED]
   invalid_percent(country) < 1% [PASSED]
All is good. No failures. No warnings. No errors.
```
