### ISSUE TITLE
Review generated check names

### ISSUE THREAD

**Issue by tombaeyens** [sodadata/soda-core#1225]
@mathissedestrooper or Benjamin should review the check names as generated by Soda Core.
 
By default, check names are the main check line.

For metric checks having nested threshold level specification: 

Given the `checks.yml` configuration:
```
checks for bitcoin:
  - min(usd):
      warn: when < 20000
      fail: when < 10000
```
expected check name:
```
min(usd) fails when < 10000
```

See also https://github.com/sodadata/soda-core/issues/1154

**Comment by tombaeyens** [comment]
```yaml
checks for PRODUCTS:
  # row_count between 10 and 1000
  - row_count between 10 and 1000
  
  # invalid_count(unit_cost) = 0
  - invalid_count(unit_cost) = 0
      valid min: 0.01
      valid max: 10000

  # invalid_percent(movement_date) warn when > 1%
  - invalid_percent(movement_date):
      valid format: date us
      warn: when > 1%
```
