### ISSUE TITLE
Issue when sending data to Soda cloud

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-core#1228]
This config does not work when sending data to Soda Cloud:

``` yaml
checks for retail_orders:
  - row_count > 0
  - invalid_percent(order_id) < 1%:
      valid format:  uuid

  - invalid_percent(product_id) < 3%:
      valid format:  uuid

  - missing_count(customer_id) < 1:
       valid format:  uuid




  #This does not work, created an issue: https://github.com/sodadata/soda-sql-v3/issues/294
  - min(discount) > 0
  - missing_count(shipping_address) < 3

  - invalid_percent(payment_method) < 25%:
      valid values: ['Cash', 'Credit Card', 'Debit Card', 'Wire Transfer']
  - failed rows:
      name: INVALID_DATES
      fail query: |
        select order_id as failed_orders
        from orders
        where ship_date < order_date;
```
