### ISSUE TITLE
Resolve variables

### ISSUE THREAD

**Issue by jasonicarter** [sodadata/soda-core#1240]
Soda Core documentation provides a [variables](https://docs.soda.io/soda-core/scan-reference.html#variables) example which should be accessible throughout the check YAML file but it doesn't work for the `name` field of checks.

```yaml
# ${variable_name} doesn't work using either "checks for" or "for each"

variables:
  CHECK_ROW_COUNT_PREVIOUS: Row Count - Change Since Previous

for each table T:
  tables:
    - MY_TABLE
  checks:
    - row_count:
        name: Row Count - Empty # works as expected
        fail: when = 0
    - change for row_count:
        name: ${CHECK_ROW_COUNT_PREVIOUS} # does not work
        fail: when < 50
```

Using `name: Row Count - Empty` works as expected (I see the correct name/label in Soda Cloud) but it doesn't work when using a variable, I get the string value `${CHECK_ROW_COUNT_PREVIOUS}`

**Use Case**: 
I'd like to create a separate global_variables.yml check file for all "global" check names like a data dictionary of sorts giving more consistent naming and so monitor names are more user friendly. 

I would then do something like `$ soda scan -d my_s -c my_config.yml global_variables.yml raw_segment_checks.yml`
