### ISSUE TITLE
YAML indentation error message

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-core#1248]
with this checks:

```yaml
checks for dim_customer:
  - invalid_count(marital_status) = 0:
    valid values:
      - W
```

Scan reports no errors:

```shell
➜ soda scan -c configuration.yml -d adventureworks checks1.yml
Soda Core 3.0.0b5
Counting invalid without valid specification does not make sense
Scan summary:
1/1 check PASSED: 
    dim_customer in adventureworks
      invalid_count(marital_status) = 0 [PASSED]
All is good. No failures. No warnings. No errors.
```

Expected : scan command will show an error because the valid values are not indented.
