### ISSUE TITLE
SodaCL column profiling

### ISSUE THREAD

**Issue by bastienboutonnet** [sodadata/soda-core#1256]
Generating and pushing profiling/EDA metrics to cloud will be done in soda-core via a profiling run.

The original proposition looks like this:

```yaml
profiling advanced:
  tables:
    - SODATEST_%
    - include SODATEST_%
    - exclude SODATEST_%
  columns:
    - TABLE%.COLNAME%
    - include TABLE%.COLNAME%
    - exclude TABLE%.COLNAME%
  max sample size: 100
  statistics: enabled  
```

We are however thinking about another top-level name along the lines of (based on a more explicit proposal from @janet-can:
```yaml
profile columns:
```

I assume the rest of the controls are going to stay the same meaning that users should configure column profiling via this canonical sodaCL spec:

```yaml
profile columns:
  tables: (required?)
    - prod_%
    - include prod_%
    - exclude dev_%
  columns: # not required
    - prod_%.some_column
    - prod_%.some_column_prefix%
    - include table.column
    - exclude table.column
  max sample size: 100 # not required and will default to a sensible number
  statistics: enabled
```

@tombaeyens can you confirm this makes sense language-wise? Also, can you explain the intention behind the `statistics` key? What does it control?

**Comment by tombaeyens** [comment]
Agreed.  Blessing given for changing the name to of the top level element to `profile column:`

**Comment by tombaeyens** [comment]
@bastienboutonnet It would be good to do a review on the proposal of the nested configuration parameters.  What are the options that all can be configured?  And how will they look like in SodaCL.  Can you do a proposal?

**Comment by bastienboutonnet** [comment]
Thanks for the questions @tombaeyens 

I can give further thoughts to what you ask. Before I do that I need some clarifications:
- what does "sample activation" mean?
- by "which metrics" I assume we may want to let users specifiy/override the metrics to be derived?
- "probably in groups or tshirt sizes or just on off switch" I don't really know what you mean. Can you rephrase a bit the way it fits in the sentence has me confused.

> should sample destination (Soda Cloud or S3) be configured under this column profiling section as well?

Am I correct in assuming you refer the sample data dataset tab? (screenshot below
<img width="1095" alt="Screenshot 2022-04-06 at 17 27 10" src="https://user-images.githubusercontent.com/4304794/162011172-85aafaad-cdf0-469e-8fb4-dd21a13f675a.png">
)

**Comment by tombaeyens** [comment]
> what does "sample activation" mean?
> Am I correct in assuming you refer the sample data dataset tab? (screenshot below

That is correct.  And sample activation just means turning on the sample creation in the SodaCL configuration.

> by "which metrics" I assume we may want to let users specifiy/override the metrics to be derived?

Yes.  The simplest approach would be just an on/off switch.  On would mean all the metrics needed to populate all the details for the column view in the UI.   We also could consider to add configuration to only calculate the basic metrics in an attempt to reduce the load on the DB while still having some metrics in the view.

I would suggest to only go for simple on/off switch first and only introduce more complex configs after we learn why customers would want more detailed configuration options.

**Comment by bastienboutonnet** [comment]
My thinking is based on the fact that we don't really know how users plan to want control over the calculated metrics that we don't offer the control for it here.

Based on the latest comment I propose the following SodaCL DSL

```yaml
profile columns:
  columns: 
    - prod_%.some_column
    - prod_%.some_column_prefix%
    - include table.column
    - exclude table.column
    - include table.%
    - include %.%
```

I'll open a new issue later where we can discuss how we give control over the metrics to be collected, and maybe involve some champions in that. What do you think @tombaeyens 

For now, this config will trigger all metrics that are part of profiling to be derived, on the selected columns.

**NOTE:**
- we have removed the concept of `tables:` since this DSL is about columns. However the use of wildcards (see above for some examples) allows users to include an entire table just as easily as they would have done so in the `tables:` section.

@tombaeyens I'd like your view on this:
I am thinking that the sample data capture, doesn't really fit into the `profile columns` concept but rather is better suited in the `table discovery` concept so I will amend the proposal made in #1257 to reflect that.
