### ISSUE TITLE
SodaCL metadata/table discovery 

### ISSUE THREAD

**Issue by bastienboutonnet** [sodadata/soda-core#1257]
Generating and pushing table information such as: name, columns, database types will be performed by soda-core.

The original proposition looks like this:

```yaml
profiling basic:
  tables:
    - SODATEST_%
    - include SODATEST_%
    - exclude SODATEST_%
  schema: enabled
```

We are however thinking about another top-level name along the lines of (based on a more explicit proposal from @janet-can:
```yaml
discover tables:
```

I assume the rest of the controls are going to stay the same meaning that users should configure column profiling via this canonical sodaCL spec:

```yaml
discover tables:
  tables:
    - SODATEST_%
    - include SODATEST_%
    - exclude SODATEST_%
  schema: enabled
```

@tombaeyens can you confirm this makes sense language-wise? Also, can you explain the intention behind the `schema` key? What does it control?

**Comment by tombaeyens** [comment]
Agreed. Blessing given for naming the SodaCL top level entry `discover tables:`

**Comment by tombaeyens** [comment]
`schema` key can be ignored and replaced with whatever keys make sense for the configuration of the table discovery feature.

**Comment by tombaeyens** [comment]
Come to think of it, it probably does not need any configuration

**Comment by bastienboutonnet** [comment]
Thanks @tombaeyens, I don't know what I would replace it with indeed so I guess it makes sense. We can always add later if we feel the need.

**Comment by bastienboutonnet** [comment]
Based on this comment: https://github.com/sodadata/soda-core/issues/1256#issuecomment-1102370385

I am proposing to move sample data caputure to this DSL rather than the `profile columns` one.

The dsl for table discovery should therefore be:

```yaml
discover tables:
  tables:
    - SODATEST_%
    - include SODATEST_%
    - exclude SODATEST_%
  collect sample data: true | false # this controls whether we capture a sample of the 
    max sample size: 100 # not required, we will default to limit 500
    sampling method: random | limit
    random see: 42 # optional and only used when `sampling method` is `random` to allow for reproducibility.
```

`collect sample data` would enable sample data collection for all tables labelled for discovery. The `max sample size` argument will control the limit of rows to be sampled. It will default to 500 if users do not override it/configure it. The `sampling method` argument will control whether we just to a `select * from table limit 100` or something `select * from table sample row (100 rows)`

**NOTES:**
- We might, based on user-interest, allow sampling in more advanced fraction-based ways (for example see snowflake: https://docs.snowflake.com/en/sql-reference/constructs/sample.html) but it would require some more explicit controls over probabilities etc. and I would rather keep the language simple for now and think about the more advanced methods if required as I don't think people will really need that granular a set of controls for this feature.
- Random-based sampling, may not work on dialects, we will therefore throw a warning to users and default to a `select * from table limit 100` approach.

@tombaeyens what do you think?

@dirkgroenen FYI, I know you had some examples around sampling in your interactive mockups for data source onboarding.
