### ISSUE TITLE
Name property on checks does not always get sent to Soda Cloud

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-core#1274]
For this config:
``` yaml
checks for retail_customers:
  - invalid_percent(customer_id) < 1%:
      name: Customer Id validity over 1 %
      valid format:  uuid

  - missing_count(customer_id) < 5:
    name: Customer Id missing should be below 5

  - invalid_percent(ip_address) < 1%:
    name: Invalid IP address
    valid format: ip_address

  - missing_count(country_code) = 0:
    name: Country code missing.

  - values in country_code must exist in ref_countries iso:
    name: Ensure valid country codes
```

I see this in Soda Cloud:
![Screenshot 2022-04-15 at 10 41 47](https://user-images.githubusercontent.com/766412/163548098-afeabac1-5873-498a-aeb3-fe9164104c68.png)
