### ISSUE TITLE
Issue with failed rows for checks like duplicates

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-core#1373]
This is causing the sync with Soda Cloud.

**Comment by albinkjellin** [comment]
I was able to replicate this issue using the reference data check:
``` yaml
checks for retail_customers:
  - values in country_code must exist in ref_countries iso:
    name: Ensure valid country codes
```
Gives this output:
```
(soda-cl-v3.0.0b15) $soda scan -d aws_postgres_retail uploaderror.yml
Soda Core 3.0.0b15
Empty file upload detected, not sending Content-Length header
No fileId received in response: {'code': 'invalid_empty_upload', 'message': 'File uploads may not be empty'}
Soda cloud error: Could not upload sample failed_rows
  | 'fileId'
Scan summary:
1/1 check PASSED: 
    retail_customers in aws_postgres_retail
      values in country_code must exist in ref_countries iso [PASSED]
1 errors.
Oops! 1 error. 0 failures. 0 warnings. 1 pass.
ERRORS:
Soda cloud error: Could not upload sample failed_rows
  | 'fileId'
Sending results to Soda Cloud
```
