### ISSUE TITLE
Snowflake Connectivity Issue 

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-core#1436]
Running into this issue:

```
  | 002003 (02000): SQL compilation error:
  | Schema 'database_name.schema_name' does not exist or not authorized.
```

When using this config:

```yaml
data_source database_name:
  type: snowflake
  connection:
    username: "user_name"
    password: "password"
    account: account_name
    database: database_name
    schema: schema_name
    warehouse: warehouse_name
    connection_timeout:
    role: role_name
    client_session_keep_alive:
    session_parameters:
      QUERY_TAG: soda-queries
      QUOTED_IDENTIFIERS_IGNORE_CASE: false
```

This might be due to the schema or the role is not being handled properly.
