### ISSUE TITLE
Secrets passed by env variables dont working

### ISSUE THREAD

**Issue by rjribeiro** [sodadata/soda-core#1496]
Hi everyone, I'm testing soda scan in bigquery with the secrets being passed via environment variables.
here the yaml:
```
data_source bigquery:
  type: bigquery
  connection:
    account_info_json: ${ DATA_QUALITY_SERVICE_ACCOUNT }
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: ${ GCP_PROJECT }
    dataset: xxxxxxx
soda_cloud:
    host: cloud.soda.io
    api_key_id: ${ SODA_API_KEY_ID }
    api_key_secret: ${ SODA_API_KEY_SECRET }
```

i passing vars in airflow BashOperator

```
import pendulum

from airflow import DAG
from airflow.models.variable import Variable
from airflow.operators.bash import BashOperator
from datetime import timedelta


from quanto_utils.utils import GCLOUD_PROJECT

# Use the same variable name that you used when you set your Airflow variables
data_quality_service_account = Variable.get("data_quality_service_account")
soda_api_key_id = Variable.get("soda_api_key_id")
soda_api_key_secret = Variable.get("soda_api_key_secret")

default_args = {
    "owner": "soda",
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
}

with DAG(
    "soda_core_scan_opbk",
    tags=["soda"],
    default_args=default_args,
    description="A simple Soda SQL scan DAG",
    schedule_interval=None,
    catchup=False,
    start_date=pendulum.datetime(2022, 6, 29, tz="UTC"),
) as dag:

    # Soda SQL Scan which runs the appropriate table scan for the ingestion
    soda_sql_scan_op = BashOperator(
        task_id="soda_scan_open_banking_openid",
        env={
            "DATA_QUALITY_SERVICE_ACCOUNT": data_quality_service_account,
            "SODA_API_KEY_ID": soda_api_key_id,
            "SODA_API_SECRET_ID": soda_api_key_secret,
            "GCP_PROJECT": GCLOUD_PROJECT,
        },
        bash_command="/opt/soda_venv/bin/python -m "
        "soda scan -d bigquery -c "
        "/opt/soda/configuration.yaml "
        "/opt/soda/testes/checks_openid.yml",
    )

```
The service account works because the test returns success, but sending the result to soda cloud does not work. Returns:
```
[2022-07-11, 20:14:25 UTC] {subprocess.py:92} INFO - Scan summary:
[2022-07-11, 20:14:25 UTC] {subprocess.py:92} INFO - 1/1 check PASSED:
[2022-07-11, 20:14:25 UTC] {subprocess.py:92} INFO -     participants in bigquery
[2022-07-11, 20:14:25 UTC] {subprocess.py:92} INFO -       freshness(created_at) [PASSED]
[2022-07-11, 20:14:25 UTC] {subprocess.py:92} INFO - 1 errors.
[2022-07-11, 20:14:25 UTC] {subprocess.py:92} INFO - Oops! 1 error. 0 failures. 0 warnings. 1 pass.
[2022-07-11, 20:14:25 UTC] {subprocess.py:92} INFO - ERRORS:
[2022-07-11, 20:14:25 UTC] {subprocess.py:92} INFO - Error while executing Soda Cloud query
[2022-07-11, 20:14:25 UTC] {subprocess.py:92} INFO -   | No API KEY and/or SECRET provided
[2022-07-11, 20:14:25 UTC] {subprocess.py:92} INFO - Sending results to Soda Cloud
[2022-07-11, 20:14:25 UTC] {subprocess.py:92} INFO - Error while executing Soda Cloud command
[2022-07-11, 20:14:25 UTC] {subprocess.py:92} INFO -   | No API KEY and/or SECRET provided
```
I tested it with the hardcoded secrets and it worked. Using soda-core 3.0.1 and soda-core-bigquery 3.0.1
Can someone help me?
