### ISSUE TITLE
Resolve variables for user-defined checks

### ISSUE THREAD

**Issue by ssulca** [sodadata/soda-core#1523]
I would like use [variables](https://docs.soda.io/soda-core/scan-reference.html#variables) on user-defined checks queries, but it doesn't work.

```yaml
# ${variable_name} doesn't work on user-defined checks queries

variables:
  TS_START: start date
  TS_END: end date 

checks for table:
  - count_column > 0 :
      count_column query: |
        select
           count(column)
        from "table"
        where created_at > '${TS_START}' and created_at < '${TS_END}'
```
resulting in
```sh
  |     cursor.execute(self.sql)
  | psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp: "${TS_START}"
  | LINE 4: where created_at > '${TS_START}' and created_at ...
```
