### ISSUE TITLE
Checks got stuck with regex-Big Query

### ISSUE THREAD

**Issue by aracastelletta** [sodadata/soda-core#1540]
When we still had the trial version of Soda Cloud, we ran the following checks and they took no longer than a minute. Now, without Soda Cloud, just using Soda Core, it takes between 30 and 40 minutes to run:
```yaml
checks for geopagos_transactions:
- row_count > 0
- row_count > 0
- min(commission_uala) > 0
- missing_count(internal_commerce_type, reference_number) = 0
- missing_percent(reference_number) > 5%
- max(commission_uala) < 100:
    name: Commission_ok
- duplicate_count(ticket_number):
    warn: when > 1
- duplicate_count(ticket_number):
    warn: when between 1 and 10
    fail: when > 10
- min(amount):
    warn: when between 1 and 10
    fail: when between -1000 and 0
- max(iva) < 1:
    filter: commission_iva = 0 
- max(iva_rate) = 0:
    filter: iva = 0
- iva_rate = 0:
    iva_rate query: |
      SELECT max(iva_rate)
      FROM geopagos_transactions
      WHERE iva=0
- invalid_count(payment_method_type) = 0:
    valid values: ['CREDIT', 'DEBIT']
- invalid_count(card_holder_document_type) = 0:
    valid values: ['DNI','LC']
- invalid_count(terminal_type) = 0:
    valid values: ['Link de Pago']
- invalid_count(card_pan) = 0:
    valid format: credit card number
- schema:
    fail:
      when required column missing:
        - card_pan
        - list_price

```
I tried to run the checks yml file again, to show you the log, but it got stuck, I am sending the output:

```
Soda Core 3.0.3
Reading configuration file "/users/aracelicastellettta/Documents/Soda/Soda_Config_BigQuery.yml"
Reading SodaCL file "/users/aracelicastellettta/Documents/Soda/Corrida_2.yml"
Scan execution starts
/Users/aracelicastellettta/.venv/lib/python3.9/site-packages/google/cloud/bigquery/client.py:535: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  warnings.warn(
Query bigquery.geopagos_transactions.aggregation[0]:
SELECT 
  COUNT(*),
  MIN(commission_uala),
  MAX(commission_uala),
  COUNT(CASE WHEN internal_commerce_type IS NULL THEN 1 END),
  COUNT(CASE WHEN reference_number IS NULL THEN 1 END),
  MIN(amount),
  MAX(CASE WHEN commission_iva = 0 THEN iva END),
  MAX(CASE WHEN iva = 0 THEN iva_rate END),
  COUNT(CASE WHEN NOT (payment_method_type IS NULL) AND NOT (payment_method_type IN ('CREDIT','DEBIT')) THEN 1 END),
  COUNT(CASE WHEN NOT (card_holder_document_type IS NULL) AND NOT (card_holder_document_type IN ('DNI','LC')) THEN 1 END),
  COUNT(CASE WHEN NOT (terminal_type IS NULL) AND NOT (terminal_type IN ('Link de Pago')) THEN 1 END),
  COUNT(CASE WHEN NOT (card_pan IS NULL) AND NOT (REGEXP_CONTAINS(card_pan, r'^[0-9]{14}|[0-9]{15}|[0-9]{16}|[0-9]{17}|[0-9]{18}|[0-9]{19}|([0-9]{4}-){3}[0-9]{4}|([0-9]{4} ){3}[0-9]{4}$')) THEN 1 END) 
FROM dw_arg.geopagos_transactions
This service is instrumented using OpenTelemetry. OpenTelemetry or one of its components could not be imported; please add compatible versions of opentelemetry-api and opentelemetry-instrumentation packages in order to get BigQuery Tracing data.
Making request: POST https://oauth2.googleapis.com/token
Query bigquery.internal_commerce_type.failed_rows[missing_count]:
SELECT * 
FROM dw_arg.geopagos_transactions 
WHERE internal_commerce_type IS NULL
Query bigquery.reference_number.failed_rows[missing_count]:
SELECT * 
FROM dw_arg.geopagos_transactions 
WHERE reference_number IS NULL
Query bigquery.terminal_type.failed_rows[invalid_count]:
SELECT * 
FROM dw_arg.geopagos_transactions 
WHERE NOT terminal_type IS NULL AND NOT terminal_type IN ('Link de Pago')
Query bigquery.card_pan.failed_rows[invalid_count]:
SELECT * 
FROM dw_arg.geopagos_transactions 
WHERE NOT card_pan IS NULL AND NOT REGEXP_CONTAINS(card_pan, r'^[0-9]{14}|[0-9]{15}|[0-9]{16}|[0-9]{17}|[0-9]{18}|[0-9]{19}|([0-9]{4}-){3}[0-9]{4}|([0-9]{4} ){3}[0-9]{4}$')
Retrying due to , sleeping 1.6s ...`
```

I am attaching a file (log-PruebaRegex.txt) with another example.
