### ISSUE TITLE
Filters on numeric checks are not applied

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-core#1541]
Issues filters on the numeric checks with soda-core for delta format and it seems they are not working.
We are reading the delta table using spark.read.format('delta').load(<path>)
and then defining the checks in scam.yml as shown below :
```yaml
checks for ao_subscription:
  - row_count > 0
  - duplicate_count(id_subscription) = 0:
      name: Duplicate row count for AO
      filter: business_unit = 'AO'

```
While when we filter the dataset while reading  like
spark.read.format('delta').load(<path>).where("business_unit = 'AO'")
and use checks as shown below, then it working as expected.
```yaml
checks for ao_subscription:
  - row_count > 0
  - duplicate_count(id_subscription) = 0
```
