### ISSUE TITLE
For each does not work with Databricks SQL endpoint

### ISSUE THREAD

**Issue by JCZuurmond** [sodadata/soda-core#1681]
The [for each logic](https://docs.soda.io/soda-cl/for-each.html) does not work when using Databricks with a SQL endpoint

Last part of the error message:

``` 
Query error: storagehub.for_each_dataset_T[0]: Database from v1 session catalog is not specified
SHOW TABLES FROM hive_metastore
  | Database from v1 session catalog is not specified
Error occurred while executing scan.
  | 'NoneType' object is not iterable
Closing unclosed connection for session b'\x01\xedd\n\xe9\x9a\x12\x82\x98\xf8\x18\x8e\t\x1bQ\xc5'
Sending request: TCloseSessionReq(sessionHandle=TSessionHandle(sessionId=THandleIdentifier(guid=b'\x01\xedd\n\xe9\x9a\x12\x82\x98\xf8\x18\x8e\t\x1bQ\xc5', secret=b'3\x8dR\x9d\x82rF\xeb\x84\x82\xcbA\x94f\x83\x9d'), serverProtocolVersion=None))
Received response: TCloseSessionResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None))
```

Configuration is as follows:

``` yaml
data_source storagehub:
  type: spark
  catalog: hive_metastore
  schema: storagehub
  method: databricks
  host: <host name>
  http_path: <HTTP path>
  token: <token>
```
