### ISSUE TITLE
Empty string is considered valid email in SQL Server

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-core#1683]
This config will not pick up empty strings in SQL Server:

```yaml
checks for dim_customer:
  - invalid_count(email_address) = 0:
      valid format: email
```
