### ISSUE TITLE
Feature: User-defined checks using a sql file

### ISSUE THREAD

**Issue by ssulca** [sodadata/soda-core#1692]
**Goal**

Support custom metrics using  **sql_file key**

This would allow reference a relative file, 
instead of including all your customized SQL queries in the custom metrics in the scan YAML file. 
Similar to [soda-sql](https://docs.soda.io/soda-sql/sql_metrics.html#custom-metrics-using-file-reference)

i.e. 
```yaml
checks for dim_product:
  - product_stock >= 50:
      product_stock sql_file: product_stock.sql
```
and `product_stock.sql` would be:
```sql
SELECT COUNT(safety_stock_level - days_to_manufacture)
FROM dim_product
```
