### ISSUE TITLE
Ability to provide a list of invalid values for validity check

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-core#1766]
Currently you can define a check by listing valid values like this:

``` yaml
checks for dim_customer:
  - invalid_count(house_owner_flag) = 0:
      valid values: ['0', '1']
```

It would be good if it was possible to list the invalid values as well:
``` yaml
checks for dim_customer:
  - invalid_count(house_owner_flag) = 0:
      invalid values: ['A', 'B']
```
