### ISSUE TITLE
unable to use camel case postgres columns with soda contracts

### ISSUE THREAD

**Issue by TianyuanCai** [sodadata/soda-core#2053]
When evaluating contracts, camel cased columns such as `countryId` doesn't get double-quoted before being templated into the sql query. As a result, this column won't be recognized, and the query would fail. I've tried several ways of escaping the quote in yaml to no avail. Do you have any suggestions for how to perform validation on camel case columns?

```yaml
dataset: country

columns:
  - name: name
    checks: 
      - type: no_missing_values
  - name: countryId
    checks: 
      - type: no_missing_values
```
