### ISSUE TITLE
Test contract with valid_values_reference_data

### ISSUE THREAD

**Issue by aixulin** [sodadata/soda-core#2155]
When I use valid_values_reference_data, there are two issues.
 The first issue is: 
When the value in column country does not exist in column id, setting a must_be_less_than condition will also result in a failure.
```
dataset: dim_employee
columns:
- name: country
  checks:
  - type: invalid_percent
    must_be_less_than: 3
    valid_values_reference_data: 
      dataset: table_b
      column: id
```
the printf log like this
```
Errors:
  error |  sodacl: Invalid reference check configuration key identity 
CheCK FAILED
  Expected invalid_ count(country)< 3
  Actual invalid_count(country) was 2
```

The second issue is:
when all the value of column country in column id value, checked result all passed ,but the contract result logs still has err like this
```
Errors:
  error |  SodaCL: Invalid reference check configuration key identity 
```
at sodal_parse.py
check 
```
            for configuration_key in check_configurations:
                if configuration_key not in [NAME, WARN, FAIL, ATTRIBUTES]:
                    self.logs.error(f"Invalid freshness configuration key {configuration_key}", location=self.location)
```
the configuration_key is identity 

Will this issue be resolved in a future version?
