### ISSUE TITLE
Order of categories influences chi_square statistic

### ISSUE THREAD

**Issue by ViacheslavP** [sodadata/soda-core#2189]
### Steps to reproduce
1. Create a simple dataset with 2:1 ration
<details>
  <summary>data.sql</summary>

For some reason, I was unable to run soda with lesser number of rows  

  ```sql
create table Employee (
                          id int primary key,
                          name varchar(255)
);

insert into Employee (id, name) values (1, 'Alice');
insert into Employee (id, name) values (2, 'Bob');
insert into Employee (id, name) values (3, 'Alice');

insert into Employee (id, name) values (11, 'Alice');
insert into Employee (id, name) values (12, 'Bob');
insert into Employee (id, name) values (13, 'Alice');

insert into Employee (id, name) values (21, 'Alice');
insert into Employee (id, name) values (22, 'Bob');
insert into Employee (id, name) values (23, 'Alice');

insert into Employee (id, name) values (31, 'Alice');
insert into Employee (id, name) values (32, 'Bob');
insert into Employee (id, name) values (33, 'Alice');

insert into Employee (id, name) values (41, 'Alice');
insert into Employee (id, name) values (42, 'Bob');
insert into Employee (id, name) values (43, 'Alice');

insert into Employee (id, name) values (51, 'Alice');
insert into Employee (id, name) values (52, 'Bob');
insert into Employee (id, name) values (53, 'Alice');
  ```
  
</details>

2. Run the following check

```yaml
checks for Employee:
  - row_count = 18

  - distribution_difference(name) < 0.05:
      method: chi_square
      distribution reference file: ./distribution.yaml
```

with `distribution.yaml`:
```yaml
dataset: employee
column: name
distribution_type: categorical
distribution_reference:
  weights:
  - 0.7
  - 0.3
  bins:
  - Alice
  - Bob
```

### Expected behavior
chi_square statistic is close to zero, since the number of Alice rows is 12 and Bob's is 6

### Actual behavior
the statistic value is high (~0.6)

### Misc

When I change the order of weights but not the bins, the statistic is OK
