### ISSUE TITLE
BigQuery documentation is misleading

### ISSUE THREAD

**Issue by milanaleksic** [sodadata/soda-core#740]
**Describe the bug**
Our [documentation](https://docs.soda.io/soda-sql/documentation/warehouse_types.html#gcp-bigquery) currently says:

```yaml
name: my_bigquery_project
connection:
    type: bigquery
    account_info: <PATH TO YOUR BIGQUERY ACCOUNT INFO JSON FILE>
    dataset: sodasql
...
```

but our code expects
1. `account_info_json`, and 
2. that property should have JSON object, not the location of it

**OS**: 
**Python Version**: *
**Soda SQL Version**: main
**Warehouse Type**: BigQuery
