### ISSUE TITLE
'row_count' is not defined

### ISSUE THREAD

**Issue by puruzio** [sodadata/soda-core#824]
**Describe the bug**
In Scan YAML, adding multiple metrics seems to cause an error.

**To Reproduce**
1. Create a new test in `scan.yml`
2. Run `soda scan ...`
3. scan fails when multiple metrics specified, resulting in the following error message. 
```
  | Test error for "row_count > 0": name 'row_count' is not defined
  | Test error for "invalid_count > 10": name 'invalid_count' is not defined
```
**Context**
__Include your scan.yml or warehouse.yml when relevant__

For example, this works:

```
table_name: Clients
metrics:
  - row_count
tests:
  - row_count > 0

```
But this fails:
```
table_name: Clients
metrics:
  - row_count
  - invalid_count
tests:
  - row_count > 0
columns:
  client:
    valid_format: number_whole
    tests:
      - invalid_count > 10
```

**OS**:  Windows 10
**Python Version**:  3.75
**Soda SQL Version**:  2.1.0b1
**Warehouse Type**: SQLSERVER
