### ISSUE TITLE
Add a way to exclude columns from samples

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-core#831]
**Is your feature request related to a problem? Please describe.**
There does not seem to be a way to exclude columns from the samples section in the yaml. This could be useful for cases when someone wants sample data but cant send an email address to Soda Cloud due to PII reasons.

**Describe the solution you'd like**
If we could add an exclude_column to the samples section that would be great.

```yml
samples:
  table_limit: 10
  failed_limit: 10
  exclude_column: email
```
