### ISSUE TITLE
No error is thrown when including tests for two tables in one scan.yml file

### ISSUE THREAD

**Issue by bjornvandijkman-ingka** [sodadata/soda-core#986]
For me it seemed intuitive to include tests for multiple tables in one scan.yml file as follows:
```
table_name: orders
metrics:
  - distinct
samples:
  table_limit: 50
columns:
  id:
    valid_format: uuid
    tests:
      - distinct == 99
  status:
    tests:
      - distinct == 5 

table_name: customers
metrics:
  - missing_count
  - missing_percentage
  - min_length
  - distinct
samples:
  table_limit: 50
metric_groups:
  - profiling
  - duplicates
columns:
  id:
    valid_format: uuid
    tests:
      - invalid_percentage == 0
      - missing_count == 0
      - distinct == 100
  first_name:
    tests:
      - min_length > 1
  last_name:
    tests:
      - min_length > 1
      - invalid_count == 0
```

Doing this results in only the customers table being used, while ignoring the orders table. I think it would be nice to have support for testing multiple tables in one file, but before such functionality is implemented it would be user-friendly if a warning/error was thrown that soda currently cannot handle testing multiple tables in one file.
